/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.Joke
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DevelopersApi {

  /**
   * By passing in the appropriate options, you can search for available joke in the system 
   * 
   * Expected answers:
   *   code 200 : Seq[Joke] (search results matching criteria)
   *   code 400 :  (bad input parameter)
   * 
   * @param searchString pass an optional search string for looking up jokes
   * @param skip number of records to skip for pagination
   * @param limit maximum number of records to return
   */
  def searchJoke(searchString: Option[String] = None, skip: Option[Int] = None, limit: Option[Int] = None): ApiRequest[Seq[Joke]] =
    ApiRequest[Seq[Joke]](ApiMethods.GET, "https://virtserver.swaggerhub.com/jeanrobert/jokes_api/1.0.0", "/joke", "application/json")
      .withQueryParam("searchString", searchString)
      .withQueryParam("skip", skip)
      .withQueryParam("limit", limit)
      .withSuccessResponse[Seq[Joke]](200)
      .withErrorResponse[Unit](400)
      

}

